packages:
  - example

catalog:
  '@types/react': ~19.2.2
  expo: ~55.0.31
  expo-image: ^55.0.11
  react: 19.2.0
  react-native: 0.83.10
  react-native-gesture-handler: ^2.30.1
  react-native-reanimated: ^4.2.1
  typescript: ~5.9.2

allowBuilds:
  unrs-resolver: true

nodeLinker: hoisted
